"""Create all tables

Revision ID: 843740ccdbc6
Revises:
Create Date: 2026-02-14 06:37:47.836188

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "843740ccdbc6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MANAGER", "DRIVER", name="userrole", native_enum=False),
            server_default="driver",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=70), nullable=False),
        sa.Column("surname", sa.String(length=70), nullable=False),
        sa.Column("phone_number", sa.String(length=24), nullable=True),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "location",
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle",
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IDLE", "BUSY", "REPAIR", name="vehiclestatus", native_enum=False),
            server_default="idle",
            nullable=False,
        ),
        sa.Column("specs", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["driver_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("driver_id"),
        sa.UniqueConstraint("license_plate"),
    )
    op.create_table(
        "order",
        sa.Column("manager_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("pickup_location_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("delivery_location_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("departure_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "LOADING",
                "TRANSIT",
                "DELIVERED",
                "CANCELED",
                name="orderstatus",
                native_enum=False,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["delivery_location_id"], ["location.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["driver_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manager_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pickup_location_id"], ["location.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    op.drop_table("vehicle")
    op.drop_table("location")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
