"""Initial migration with uuidv7

Revision ID: e3ea197a772f
Revises: 01685d5f3120
Create Date: 2026-04-28 00:35:45.012064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3ea197a772f"
down_revision: Union[str, Sequence[str], None] = "01685d5f3120"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False, comment="Email"),
        sa.Column("password", sa.String(length=60), nullable=False, comment="Пароль"),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MANAGER", "DRIVER", name="userrole", native_enum=False),
            server_default="driver",
            nullable=False,
            comment="Роль",
        ),
        sa.Column("name", sa.String(length=70), nullable=False, comment="Имя"),
        sa.Column("surname", sa.String(length=70), nullable=False, comment="Фамилия"),
        sa.Column("phone_number", sa.String(length=24), nullable=True, comment="Номер телефона"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "location",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False, comment="Город"),
        sa.Column("address", sa.String(length=200), nullable=False, comment="Адрес"),
        sa.Column("latitude", sa.Float(), nullable=True, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="Долгота"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=False, comment="Государственный номер"),
        sa.Column(
            "status",
            sa.Enum("IDLE", "BUSY", "REPAIR", name="vehiclestatus", native_enum=False),
            server_default="IDLE",
            nullable=False,
            comment="Статус транспорта",
        ),
        sa.Column(
            "specs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Характеристики транспорта",
        ),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True, comment="Номер водительского удостоверения"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["driver_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("driver_id"),
        sa.UniqueConstraint("license_plate"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("manager_id", sa.UUID(as_uuid=False), nullable=False, comment="ID менеджера"),
        sa.Column("driver_id", sa.UUID(as_uuid=False), nullable=True, comment="ID водителя"),
        sa.Column("vehicle_id", sa.UUID(as_uuid=False), nullable=True, comment="ID автомобиля"),
        sa.Column("pickup_location_id", sa.UUID(as_uuid=False), nullable=False, comment="ID места отправления"),
        sa.Column("delivery_location_id", sa.UUID(as_uuid=False), nullable=False, comment="ID места назначения"),
        sa.Column("departure_date", sa.DateTime(timezone=True), nullable=False, comment="Дата отправления"),
        sa.Column("arrival_date", sa.DateTime(timezone=True), nullable=False, comment="Дата прибытия"),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "ASSIGNED", "LOADING", "TRANSIT", "DELIVERED", "CANCELED", name="orderstatus", native_enum=False
            ),
            server_default="new",
            nullable=False,
            comment="Статус",
        ),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False, comment="Стоимость"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("modified_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["delivery_location_id"], ["location.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["driver_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manager_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["modified_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pickup_location_id"], ["location.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    op.drop_table("vehicle")
    op.drop_table("location")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
